### ISSUE TITLE
iOS not sending push messages

### ISSUE THREAD

**Issue by Ehesp** [ghaiklor/sails-service-pusher#53]
With exactly the same cert/key and config, the example in the `apn` module works fine (https://github.com/argon/node-apn/blob/master/examples/sending-to-multiple-devices.js). 

Using this service, with the following:

```
// Pusher service
ios: PusherService('ios', {
        provider: {
            cert: 'cert.pem',
            key: 'key.pem',
            production: true
        },
        notification: {
            title: 'TITLE',
            body: 'BODY',
            icon: 'ICON',
            sound: 'SOUND',
            badge: 'BADGE',
            payload: {
                foo: 'bar',
                bar: 'foo'
            }
        }
    })
```

```
   Pusher.ios.send(['MY_TOKEN'])
        .then(function(r) {
          console.log('done');
          cb();
        })
        .catch(function(e) {
          console.log(e)
          cb();
        })
```

This returns the `console.log('done')` with no errors but we never get the push.

**Comment by ghaiklor** [comment]
@Ehesp it should write to the console response from Apple server if something wrong. You can try to play around with these lines - https://github.com/ghaiklor/sails-service-pusher/blob/dev/src/APNNotification.js#L18. Maybe there some issue with printing to console on error. We are using this module in one of projects and works fine. Could be some specific case.

**Comment by Salakar** [comment]
I'm also having the same issue as @Ehesp - shows no errors, doesn't send, but works fine if I use the raw `node-apn` lib.

**Comment by ghaiklor** [comment]
@Ehesp @Salakar I'm currently don't have testing app and certificates. Do you know some services to test the push notifications ?

**Comment by Ehesp** [comment]
@ghaiklor How can we share this with you? We have certs but they're tied to an internal app which is on Test Flight.

**Comment by Ehesp** [comment]
@ghaiklor did some more debugging but no joy still:
- I modified what you said above:

```
    _this.getProvider().on('error', function (error) {
      console.log('ERROR');
      console.log(error)
    }).on('transmissionError',function(error) {
      console.log('TRANS ERROR');
      console.log(error)
    });
```

None of these log.
- I then set the env to `DEBUG=apn`, which logs:

```
Wed, 03 Feb 2016 11:02:48 GMT apn Initialising connection
Wed, 03 Feb 2016 11:02:48 GMT apn Loading Credentials
Wed, 03 Feb 2016 11:02:48 GMT apn 1 left to send
Wed, 03 Feb 2016 11:02:49 GMT apn Connection established
Wed, 03 Feb 2016 11:02:49 GMT apn Socket drained 0
Wed, 03 Feb 2016 11:02:49 GMT apn 0 left to send
Wed, 03 Feb 2016 11:02:49 GMT apn 0 left to send
```
- Also after the `send()` method, the following logs undefined:

```
.then(console.log.bind(console))
.catch(console.error.bind(console));
``
```

**Comment by Ehesp** [comment]
@ghaiklor If you console log out `notification` [here](https://github.com/argon/node-apn/blob/master/lib/connection.js#L728), the aps payload is present as an object. Console log it out on line [741](https://github.com/argon/node-apn/blob/master/lib/connection.js#L741) and it's undefined.

However even after removing the code inbetween (so its no longer undefined), it still doesn't send the push message. The device there is fine too.

**Comment by ghaiklor** [comment]
@Ehesp what about breaking changes in node-apn module ? Does it make sense ? If I'm not wrong, published package has the latest node-apn version. Try to check `createNotification()` method here - https://github.com/ghaiklor/sails-service-pusher/blob/dev/src/APNNotification.js#L41. Here I'm building the notification object according to node-apn documentation.

**Comment by Ehesp** [comment]
Yeah that's all up to date... I've no idea :(

Using APN:

```
      tokens.forEach(function(token, i) {
        var note = new apn.notification();
        note.setAlertText("Hello, from node-apn! You are number: " + i);
        note.badge = i;

        service.pushNotification(note, token);
      });
```

Where service is:

```
var service = new apn.connection({ production: true });
```

This works, just trying to find reference to what `setAlertText` is?

**Comment by Ehesp** [comment]
@ghaiklor So I got it working, but not sure why!

So here: https://github.com/ghaiklor/sails-service-pusher/blob/dev/src/APNNotification.js#L55 (line is different in compiled source though), I added in:

`notification.setAlertText('hello there')` and got a push notification through.

Here is mentions all of the params: https://github.com/argon/node-apn/blob/56dc1cf3e0f0d20802a98c295c0a80528cd0afcb/doc/notification.markdown

So maybe it needs to use the setter functions instead of building it manually?

**Comment by Ehesp** [comment]
See the PR ^^ This works, the title and body are correctly set and the message comes through here. Would need to test the sound and badge, but I assume they work as it does follow what the docs say.

**Comment by Ehesp** [comment]
Also the sound and badge were not working, not sure about the payload yet. But updated the PR with the fix for sound and badge... Also, icon is never set anywhere so not sure what this is for (on iOS?).

**Comment by ghaiklor** [comment]
@Ehesp great. Older versions of `node-apn` were just fine with custom payload object.

> Also the sound and badge were not working, not sure about the payload yet

It's important parts of module, I can't merge if payload is not sending :smiley_cat: 

> Also, icon is never set anywhere so not sure what this is for (on iOS?).

It was done for Android implementation and has nothing for iOS devices.

**UPD:** So is PR working now with all parameters?

**Comment by Ehesp** [comment]
Okay I'll test the payload when I can!

Also the last `node-apn` release was October, so this couldn't have been working with the latest version since then?

**Comment by Ehesp** [comment]
@ghaiklor Just tested with my PR changes, payload comes through :)

**Comment by Ehesp** [comment]
Cheers, can we push a version up?

**Comment by ghaiklor** [comment]
@Ehesp waiting for Travis CI - https://travis-ci.org/ghaiklor/sails-service-pusher/builds/106969835
Travis is responsible for publishing new versions.

**Comment by ghaiklor** [comment]
@Ehesp you can try it out. Reopen this issue if it will not work. Anyway, I hope this works 'cause I did change nothing in your code and believe you :smiley_cat:

**Comment by Ehesp** [comment]
Will do! :running:

Update: Yep, seems to be working :)

**Comment by ghaiklor** [comment]
@Ehesp great, thanks for your work :+1:
